on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    container: python
    steps:
      - uses: actions/checkout@v1
        
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: waldronlab/metagenomicsclient
          tag_with_ref: true
          tag_with_sha: true
          tags: latest
