name: dockerpush

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          push: true
          repository: waldronlab/metagenomicsclient
          tags: latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}